name: Publish packages

on:
    push:
        branches:
            - main

jobs:
    Publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            # - name: Setup Node
            #   uses: actions/setup-node@v3
            #   with:
            #     node-version: '18'
            # - name: Set NPM token
            #   run: npm set //registry.npmjs.org/:_authToken ${{secrets.NPM_PUBLISH_TOKEN}}
            # - name: Install dependencies
            #   run: yarn
            # - name: Build
            #   run: yarn build
            # - name: Stash changes that build might have caused by build
            #   run: git stash
            # - name: Publish
            #   run: yarn lerna publish from-package --yes
